In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp

## Практика numpy

In [16]:
c = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

print(c)
print(len(c))

[[1 2 3 4]
 [5 6 7 8]]
2


In [17]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

In [18]:
b = np.logspace(0, 4, 12)
print(b)

[1.00000000e+00 2.31012970e+00 5.33669923e+00 1.23284674e+01
 2.84803587e+01 6.57933225e+01 1.51991108e+02 3.51119173e+02
 8.11130831e+02 1.87381742e+03 4.32876128e+03 1.00000000e+04]


#### Математические функции

In [19]:
np.cos(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.log(b)

array([0.        , 0.83730367, 1.67460734, 2.51191101, 3.34921468,
       4.18651835, 5.02382202, 5.86112569, 6.69842936, 7.53573303,
       8.3730367 , 9.21034037])

In [27]:
## операции

a = np.linspace(5, 45, 10)
b = np.linspace(9, 80, 10)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 14.          26.33333333  38.66666667  51.          63.33333333
  75.66666667  88.         100.33333333 112.66666667 125.        ]
[ -4.          -7.44444444 -10.88888889 -14.33333333 -17.77777778
 -21.22222222 -24.66666667 -28.11111111 -31.55555556 -35.        ]
[  45.          159.50617284  344.13580247  598.88888889  923.7654321
 1318.7654321  1783.88888889 2319.13580247 2924.50617284 3600.        ]
[0.55555556 0.55921053 0.56053812 0.56122449 0.56164384 0.56192661
 0.56213018 0.56228374 0.5624037  0.5625    ]


In [30]:
print(a - b)
print(np.sort(a - b))

[ -4.          -7.44444444 -10.88888889 -14.33333333 -17.77777778
 -21.22222222 -24.66666667 -28.11111111 -31.55555556 -35.        ]
[-35.         -31.55555556 -28.11111111 -24.66666667 -21.22222222
 -17.77777778 -14.33333333 -10.88888889  -7.44444444  -4.        ]


## Практика pandas

In [5]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

Yes   No
0   50  131
1   21    2

In [6]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [32]:
one_dict = {'one': pd.Series([11,21,43], index=['a','b','c']),
             'two': pd.Series([15,27,33,48], index=['a','b','c','d']),
             'three': pd.Series([54,63,76,81], index=['a','b','c','d'])}
df = pd.DataFrame(one_dict)
df

one  two  three
a  11.0   15     54
b  21.0   27     63
c  43.0   33     76
d   NaN   48     81

In [33]:
df.columns

Index(['one', 'two', 'three'], dtype='object')

In [34]:
df.values

array([[11., 15., 54.],
       [21., 27., 63.],
       [43., 33., 76.],
       [nan, 48., 81.]])

In [36]:
df[1:3]

one  two  three
b  21.0   27     63
c  43.0   33     76

## Библиотеки и их версии

pandas, numpy, PyTorch

In [38]:
print(np.__version__)

1.21.2


In [39]:
print(pd.__version__)

1.3.3


In [42]:
import torch
print(torch.__version__)

1.9.0
